version: '2'
services:
  app:
    build: .
    volumes:
      - .:/wow:delegated
      - node-modules:/wow/node_modules/
      - client-node-modules:/wow/client/node_modules/
    working_dir: /wow
    ports:
      - 3000:3000
    links:
      - db
    environment:
      DATABASE_URL: postgres://wow:wow@db/wow
    command: yarn start
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=wow
      - POSTGRES_DB=wow
      - POSTGRES_PASSWORD=wow
volumes:
  node-modules:
  client-node-modules:
