version: '2'
services:
  app:
    image: node:8.12
    volumes:
      - .:/wow:delegated
      - node-modules:/wow/node_modules/
    working_dir: /wow
  nycdb:
    build: .
    volumes:
      - .:/wow:delegated
    working_dir: /wow
    links:
      - db
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=wow
      - POSTGRES_DB=wow
      - POSTGRES_PASSWORD=wow
volumes:
  node-modules:
